@echo off
echo export { StockTransferPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\products\transfers\page.tsx"
echo export { ReorderAlertsPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\products\reorder\page.tsx"
echo export { BatchExpiryPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\products\batch-expiry\page.tsx"
echo export { ProjectsAllPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\projects\all\page.tsx"
echo export { ProjectTimePage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\projects\time\page.tsx"
echo export { ProjectBudgetsPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\projects\budgets\page.tsx"
echo export { ProjectProfitabilityPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\projects\profitability\page.tsx"
echo export { LeadsPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\crm\leads\page.tsx"
echo export { OpportunitiesPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\crm\opportunities\page.tsx"
echo export { SalesPipelinePage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\crm\pipeline\page.tsx"
echo export { ContactsPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\crm\contacts\page.tsx"
echo export { AnnualBudgetPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\budgeting\annual\page.tsx"
echo export { DepartmentBudgetsPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\budgeting\departments\page.tsx"
echo export { ForecastingPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\budgeting\forecasting\page.tsx"
echo export { BudgetVariancePage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\budgeting\variance\page.tsx"
echo export { AssetRegisterPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\assets\register\page.tsx"
echo export { DepreciationPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\assets\depreciation\page.tsx"
echo export { AssetCategoriesPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\assets\categories\page.tsx"
echo export { AIAssistantPage as default } from "@/components/pages-exports"; > "app\(organisation)\(routes)\[organizationId]\dashboard\[userId]\ai-assistant\page.tsx"
echo All pages created successfully!
